In [79]:
import networkx as nx
import pandas as pd
import pickle
from collections import defaultdict
import ast
import re

### Convert KG to (head[tab]rel[tab]tail) format for Anyburl

+ remove or merge non-causal relations
+ remove AD-node to mine rules

In [3]:
# process KG to remove non-causal relations and remove AD node
kg_path = "../data/KG/ad_network_with_reverse_edges.pkl"
non_causal_relations = ['positive_correlation',
    'association',
    'causes_no_change',
    'negative_correlation']

with open(kg_path,"rb")as f:
    G = pickle.load(f)

def change_kg(G, non_causal_relations:list, output:str, causal_only=True, no_AD=True):
    
    # remove non_causal relations
    unique_rels = set()   
    edges_to_remove = [] 
    for u,v,rel,data in G.edges(data=True, keys=True):
        unique_rels.add(rel)
        if rel in non_causal_relations:
            edges_to_remove.append((u,v,rel))
    if causal_only == True:
        G.remove_edges_from(edges_to_remove)
        # save causal-only-KG
        with open(output, 'wb') as f:
            pickle.dump(G, f)
    if no_AD: 
        # remove AD node
        for n in G.nodes():
            if "Alzheimer Disease" in n:
                ad_node = n
        G.remove_node(ad_node)

        # save causal-only-KG
        with open(output, 'wb') as f:
            pickle.dump(G, f)
    return G

In [10]:
def get_anyburl_df(G:nx.MultiDiGraph, non_causal_relations=None, health_kg=True, output = 'train.txt'):

    triples = []
    i = 0
    if health_kg:
        for u, v, rel, attr in G.edges(data=True, keys=True):
            u_name = G.nodes[u]['bel']
            v_name = G.nodes[v]['bel']
            rel_type = attr.get('type')
            triples.append([u_name, rel_type, v_name])
    elif non_causal_relations is not None:
        for u, v, rel, data in G.edges(data=True, keys=True): 
            if 'rev_' not in rel and rel not in non_causal_relations:
                triples.append([u, rel, v])
    else:
        for u, v, rel, data in G.edges(data=True, keys=True): 
            if 'rev_' not in rel:
                triples.append([u, rel, v])
                    
    df = pd.DataFrame(triples)
    df.to_csv(output, sep='\t', header=False, index=False)
    return df

In [11]:
# get AnyBURL train.txt for causal_relation.txt no_ad_causal.txt
with open('../data/KG/no_ad_causal_only.pkl', 'rb') as f:
    G_no_ad = pickle.load(f)
with open('../data/KG/ad_causal_only.pkl','rb') as f:
    G_causal = pickle.load(f)
with open('../data/KG/healthy_aging_kg.pkl', 'rb') as f:
    healthy_kg = pickle.load(f)

# convert to train.txt file
df_all = get_anyburl_df(G=G, health_kg=False,output='../data/train.txt')
df_no_ad = get_anyburl_df(G_no_ad,non_causal_relations,False,'../data/train_no_ad.txt')
df_causal = get_anyburl_df(G_causal, non_causal_relations, False, '../data/train_causal.txt')
df_health = get_anyburl_df(G=healthy_kg,health_kg=True, output='../data/train_healthy.txt')

In [12]:
df_all

,0,1,2
0,"g(HGNC:""BDNF"")",decreases,"p(HGNC:""APP"",frag(""672_713""))"
1,"g(HGNC:""BDNF"")",increases,"g(HGNC:""SORL1"")"
2,"g(HGNC:""BDNF"")",increases,"p(HGNC:""BDNF"")"
3,"g(HGNC:""PPP1CC"")",association,"path(MESH:""Alzheimer Disease"")"
4,"g(HGNC:""PPP1CC"")",association,"bp(MESH:""Polymorphism, Single Nucleotide"")"
...,...,...,...
7851,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""NR4A2"")"
7852,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""ADAM10"")"
7853,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""FOS"")"
7854,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""SIRT1"")"
7855,"composite(p(HGNC:""TNFRSF12A""),p(HGNC:""TNFRSF25""))",association,"path(MESH:""Intervertebral Disc Degeneration"")"

In [14]:
df_no_ad

,0,1,2
0,"g(HGNC:""BDNF"")",decreases,"p(HGNC:""APP"",frag(""672_713""))"
1,"g(HGNC:""BDNF"")",increases,"g(HGNC:""SORL1"")"
2,"g(HGNC:""BDNF"")",increases,"p(HGNC:""BDNF"")"
3,"g(HGNC:""VLDLR"")",increases,"bp(GO:""lipid metabolic process"")"
4,"g(HGNC:""VLDLR"")",increases,"bp(GO:""central nervous system development"")"
...,...,...,...
5070,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(FPLX:""CREB"")"
5071,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""NR4A2"")"
5072,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""ADAM10"")"
5073,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""FOS"")"
5074,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""SIRT1"")"

In [13]:
df_causal

,0,1,2
0,"g(HGNC:""BDNF"")",decreases,"p(HGNC:""APP"",frag(""672_713""))"
1,"g(HGNC:""BDNF"")",increases,"g(HGNC:""SORL1"")"
2,"g(HGNC:""BDNF"")",increases,"p(HGNC:""BDNF"")"
3,"g(HGNC:""VLDLR"")",increases,"bp(GO:""lipid metabolic process"")"
4,"g(HGNC:""VLDLR"")",increases,"bp(GO:""central nervous system development"")"
...,...,...,...
5272,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(FPLX:""CREB"")"
5273,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""NR4A2"")"
5274,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""ADAM10"")"
5275,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""FOS"")"
5276,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",decreases,"p(HGNC:""SIRT1"")"

In [15]:
df_health

,0,1,2
0,"r(MGI:""Bace1"")",regulates,"a(CHEBI:""amyloid-beta"")"
1,"a(CHEBI:""amyloid-beta"")",regulates,"bp(GOBP:""lipid homeostasis"")"
2,"a(CHEBI:""amyloid-beta"")",regulates,"bp(GOBP:""memory"")"
3,"a(CHEBI:""amyloid-beta"")",regulates,"bp(GOBP:""memory"")"
4,"a(CHEBI:""amyloid-beta"")",regulates,"bp(GOBP:""memory"")"
...,...,...,...
7405,"g(HGNCGENEGROUP:""Glutamate metabotropic recept...",regulates,"bp(GOBP:""long-term synaptic depression"")"
7406,"bp(PW:""ion homeostasis pathway"")",regulates,"bp(GOBP:""cell death"")"
7407,"bp(PW:""kinase mediated signaling pathway"")",regulates,"bp(GOBP:""learning"")"
7408,"bp(PW:""kinase mediated signaling pathway"")",regulates,"bp(GOBP:""memory"")"
7409,"bp(PW:""kinase mediated signaling pathway"")",regulates,"bp(GOBP:""long-term synaptic potentiation"")"

### Compare rules between files

In [44]:
# Define the scoring hierarchy
scores_map = {
    'directly_increases': 1.0,
    'increases': 0.8,
    'positive_correlation': 0.5,
    'association': 0.1,
    'causes_no_change': 0.0,
    'negative_correlation': -0.5,
    'decreases': -0.8,
    'directly_decreases': -1.0
}

In [ ]:
def load_rules(filepath):
    """Returns a set of the logic strings and a dict mapping logic to confidence."""
    rules_logic = set()
    rule_data = {}

    rules_logic = set()
    rule_data = {}
    with open(filepath, 'r') as f:
        for line in f:
            if "<=" not in line: continue  # Skip headers
            parts = line.strip().split("\t")
            # AnyBURL format: [Predicted_Count] [Correct_Count] [Confidence] [Rule_Logic]
            conf = float(parts[2])
            logic = parts[3]
            rules_logic.add(logic)
            rules_data[logic] = conf
            # # filter for AD
            # if "Alzheimer Disease" in logic and 'p(HGNC' in logic:
            #     rules_logic.add(logic)
            #     rule_data[logic] = conf
            # if "Alzheimer Disease" in logic and 'g(HGNC' in logic:
            #     rules_logic.add(logic)
            #     rule_data[logic]=conf
    return rules_logic, rule_data

### NO-AD-Graph mined rules

Get ad-linked nodes: the nodes that have direct causal edge to ad-node

In [ ]:
ad_linked_df = pd.read_csv("../data/ad_linked_nodes.csv", sep='\t')
increase_ad_df = ad_linked_df[ad_linked_df['Relation'].str.contains('increases', na=False)]
decrease_ad_df = ad_linked_df[ad_linked_df['Relation'].str.contains('decreases', na=False)]

increase_ad_nodes = list(increase_ad_df['Node'])
decrease_ad_nodes = list(decrease_ad_df['Node'])
print(f'{len(increase_ad_nodes)} nodes that increase AD:\n', increase_ad_nodes, f'\n\n{len(decrease_ad_nodes)} nodes that decrease AD:\n', decrease_ad_nodes)

26 nodes that increase AD:
 ['g(HGNC:"CD33")', 'g(HGNC:"RFC1",var("G,80,A"))', 'g(HGNC:"CR1")', 'g(HGNC:"MTHFR",var("C,677,T"))', 'g(HGNC:"CLU")', 'g(HGNC:"PICALM")', 'p(HGNC:"APP",var("N,10,Y"))', 'p(HGNC:"APP")', 'p(HGNC:"APP",var("A,713,T"))', 'p(HGNC:"PSEN1")', 'p(HGNC:"H3F3A",pmod(Ub))', 'p(HGNC:"H3F3A",var("P,T,231"))', 'p(HGNC:"MTHFR",var("A,677,V"))', 'p(HGNC:"APP",frag("1_8"))', 'p(HGNC:"APP",frag("9_16"))', 'p(HGNC:"LRP8")', 'p(HGNC:"DYRK1A")', 'p(HGNC:"MMP2")', 'p(HGNC:"GRN")', 'p(HGNC:"APP",frag("1_16"))', 'p(HGNC:"BACE1")', 'p(HGNC:"AGER")', 'p(HGNC:"MAPT",pmod(Ph))', 'p(HGNC:"S100A9")', 'p(HGNC:"APP",frag("672_713"))', 'p(HGNC:"LRP1")']

4 nodes that decrease AD:
 ['g(HGNC:"APP",var("A,673,T"))', 'p(HGNC:"IL1B")', 'p(HGNC:"PLAT")', 'p(HGNC:"CCR5")']

analysis on rules mined from No-AD-KG

In [16]:
column_names = ["Predicted_Count", "Correct_Count", "Confidence", "Rule_Logic"]
df_nad_100 = pd.read_csv("../results/no_ad/rules.txt-100", sep='\t', header=0, names=column_names)
df_nad_300 = pd.read_csv("../results/no_ad/rules.txt-300", sep='\t',header=0, names=column_names)
df_nad_600 = pd.read_csv("../results/no_ad/rules.txt-600", sep='\t',header=0, names=column_names)

## Extract rules containing increase_ad nodes

In [91]:
def if_contains(row_string, match_list):
    replaced = row_string.replace('""','"')
    for node in match_list:
        if node in replaced:
            return True
        
    return False

def extract_target_rules(df, match_list, output, confidence_threshold = 0.5, correct_count_threshold=2):
    df = df.sort_values(by=['Confidence','Correct_Count'], ascending=[False,False])
    filtered_df = df[(df['Confidence']>=confidence_threshold) & (df_nad_100['Correct_Count']>correct_count_threshold)]
    increase_ad_rules = filtered_df[filtered_df['Rule_Logic'].apply(lambda x: if_contains(str(x), match_list))]
    increase_ad_rules.to_csv(output, sep='\t')
    print(f"Found {len(increase_ad_rules)} target rules")
    return increase_ad_rules
df_nad_increase_100 = extract_target_rules(df_nad_100, increase_ad_nodes, 'nad_100_rules.txt')
for i in df_nad_increase_100['Rule_Logic']:
    print(i)

Found 82 target rules
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""PSEN2"")",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"p(HGNC:""APP"",frag(""672_711""))")
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= increases(X,"deg(p(HGNC:""APP"",frag(""672_711"")))")
increases("p(HGNC:""PSEN1"")",Y) <= decreases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y)
increases("act(p(HGNC:""PSEN1""))",Y) <= increases("act(p(HGNC:""PSEN2""))",Y)
increases("act(p(HGNC:""PSEN2""))",Y) <= increases("act(p(HGNC:""PSEN1""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y)
increases("p(HGNC:""NFKB2"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases("p(HGNC:""IL10"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2B""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases(Y,"p(HGNC:""BCL2L11"")")
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= decreases(Y,"sec(p(HGNC:""GNRH1""))")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN3B""))",X)
increases(X,"deg(p(HGNC:""APP""))") <= directly_increases(X,"rxn(reactants(p(HGNC:""APP"")),products(a(CHEBI:""amyloid-beta"")))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""GSK3B"",var(""Ph,S,9""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""FTL"")",Y)
increases(X,"act(p(HGNC:""MAPK3""))") <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",X)
increases(X,"act(p(HGNC:""MAPK1""))") <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",X)
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= decreases("a(MESH:""Cholinesterase Inhibitors"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""CCR2"")",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2C""))",X)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN3A""))",X)
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= increases(Y,"p(HGNC:""NFKB2"")")
increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",Y) <= increases("complex(p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2A""))",X)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2D""))",X)
increases("complex(p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",Y)
increases("a(CHEBI:""nefiracetam"")",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases("a(CHEBI:""donepezil"")",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases(X,"a(CHEBI:""glutamate(1-)"")") <= regulates(X,"p(HGNC:""APP"",frag(""672_713""))")
increases("complex(a(CHEBI:""nefiracetam""),p(HGNC:""PRKCA""))",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= increases("p(HGNC:""IL10"")",Y)
increases(X,"p(HGNC:""NFKB2"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases(X,"bp(GO:""production of molecular mediator involved in inflammatory response"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""ADAM10""),ma(pep))",Y)
increases(X,"p(HGNC:""APP"")") <= decreases("a(CHEBI:""curcumin"")",X)
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"bp(GO:""microglial cell activation involved in immune response"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"bp(GO:""regulation of inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"bp(GO:""regulation of ryanodine-sensitive calcium-release channel activity"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= regulates("p(HGNC:""PSEN1"")",X)
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= decreases("p(HGNC:""INS"")",X)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNCGENEFAMILY:""Glutamate ionotropic receptor NMDA type subunits""))",X)
increases("a(MESH:""Astrocytes"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"a(CHEBI:""amyloid-beta"")") <= increases("complex(p(HGNC:""APOE""),p(HGNC:""LRP8""))",X)
increases(X,"p(HGNC:""BACE1"")") <= decreases("a(CHEBI:""dorsomorphin"")",X)
increases("bp(GO:""microglial cell activation involved in immune response"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases("a(CHEBI:""galanthamine"")",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases(X,"a(CHEBI:""amyloid-beta"")") <= increases(X,"act(p(HGNC:""BACE1""))")
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"act(p(HGNC:""BACE1""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""rutin"")",Y)
increases(X,"a(CHEBI:""gamma-aminobutyric acid"")") <= regulates(X,"p(HGNC:""APP"",frag(""672_713""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""DKK1"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"act(p(HGNC:""AGER""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""CTNNB1"",pmod(Ph))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""Amylin"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""LEP"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""ADAM10""))",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("complex(a(MESH:""Lipoproteins, LDL""),p(HGNC:""APOB""))",X)
increases(X,"act(p(HGNC:""AGER""))") <= increases(X,"p(HGNC:""DKK1"")")
increases(X,"p(HGNC:""DKK1"")") <= increases(X,"act(p(HGNC:""AGER""))")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("act(p(FPLX:""PRKAC""),ma(kin))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""PIN1"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"r(HGNC:""BACE1"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"act(p(FPLX:""JNK""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""PPARG"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"a(CHEBI:""nitric oxide"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""JUN"",pmod(Ph))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""MAPT"",var(""P,S,396""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"complex(GO:""neurofibrillary tangle"")")
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""APP"",var(""P,T,668""))",Y)
increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",Y) <= increases(Y,"act(p(HGNC:""MAPK3""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= directly_increases(X,"p(HGNC:""MAPT"",pmod(Ph))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""vitamin E"")",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= decreases("a(CHEBI:""17beta-estradiol"")",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""APP"",var(""P,T,668""))",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases("p(HGNC:""IL1A"")",X)
increases(X,"p(HGNC:""APP"")") <= increases(X,"p(HGNC:""PSEN1"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("bp(GO:""Wnt signaling pathway, planar cell polarity pathway"")",X)

In [92]:
df_nad_increase_300 = extract_target_rules(df_nad_300, increase_ad_nodes, 'nad_300_rules.txt')
for i in df_nad_increase_300['Rule_Logic']:
    print(i)

Found 184 target rules
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"p(HGNC:""APP"",frag(""672_711""))")
increases("p(HGNC:""PSEN1"")",Y) <= decreases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y)
increases("p(HGNC:""NFKB2"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2B""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases(Y,"p(HGNC:""BCL2L11"")")
increases(X,"deg(p(HGNC:""APP""))") <= directly_increases(X,"rxn(reactants(p(HGNC:""APP"")),products(a(CHEBI:""amyloid-beta"")))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""GSK3B"",var(""Ph,S,9""))",Y)
increases(X,"act(p(HGNC:""MAPK1""))") <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",X)
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= decreases("a(MESH:""Cholinesterase Inhibitors"")",Y)
increases("complex(p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""A2M"")",X)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("p(HGNC:""ABCA2"")",X)
increases(X,"p(HGNC:""APP"")") <= decreases("a(CHEBI:""thyroid hormone"")",X)
increases("p(HGNC:""APP"",var(""P,T,668""))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""BACE1"")",Y) <= increases(Y,"act(p(HGNC:""MSR1""))")
increases("p(HGNC:""APP"")",Y) <= increases(Y,"act(complex(FPLX:""PPP3""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""CACNG2"")",Y)
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""APOE"",var(""R,132,S""))",Y)
increases(X,"p(HGNC:""DKK1"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""APP"")",Y) <= decreases(Y,"sec(p(HGNC:""CLU""))")
increases(X,"a(CHEBI:""reactive oxygen species"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("g(HGNC:""APP"",var(""G,717,C""))",Y)
increases("p(HGNC:""APP"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases(X,"act(p(HGNC:""AGER""))") <= decreases(X,"act(p(HGNC:""BDNF""))")
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= directly_decreases(Y,"bp(GO:""calcium ion homeostasis"")")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("g(HGNC:""APP"",var(""G,275341,C""))",Y)
increases("p(HGNC:""AGER"")",Y) <= increases("p(HGNC:""EIF2A"",pmod(Ph))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"sec(p(HGNC:""CLU""))")
increases("p(HGNC:""BACE1"")",Y) <= decreases(Y,"bp(MESH:""Long-Term Potentiation"")")
increases(X,"rxn(reactants(p(HGNC:""APP"")),products(p(HGNC:""APP"",frag(""672_713""))))") <= increases(X,"g(HGNC:""APP"")")
increases(X,"p(HGNC:""APP"")") <= increases(X,"p(HGNC:""IL1RN"")")
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"act(p(HGNC:""NTRK2""))")
increases("deg(p(HGNC:""APP""))",Y) <= increases("g(HGNC:""APP"",var(""G,275341,C""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""CLU"")",X)
increases(X,"act(p(HGNC:""AGER""))") <= decreases(X,"sec(p(HGNC:""CLU""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("g(HGNC:""APP"",var(""G,717,C""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("g(HGNC:""PSEN1"")",Y)
increases("a(CHEBI:""metformin"")",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y)
increases(X,"act(p(HGNC:""AGER""))") <= increases("p(HGNC:""APOE"",var(""R,132,S""))",X)
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""APP"",frag(""740_770""))",Y)
increases("p(HGNC:""BACE1"")",Y) <= decreases(Y,"act(p(HGNC:""NTRK2""))")
increases("p(HGNC:""BACE1"")",Y) <= increases("p(HGNC:""APOE"",var(""R,132,S""))",Y)
increases("act(p(FPLX:""JNK""))",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""))",Y)
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= increases("act(p(HGNC:""QPCT""),ma(pep))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= regulates(X,"bp(GO:""axonal transport"")")
increases(X,"a(CHEBI:""calcium(2+)"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(MGI:""Gcg"")",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("act(p(HGNC:""ADAM17""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""KLF10"")",Y)
increases("p(HGNC:""APP"")",Y) <= increases(Y,"tloc(a(CHEBI:""phosphatidyl-L-serine""),fromLoc(MESH:""Cell Membrane""),toLoc(MESH:""Cell Surface Extensions""))")
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"sec(p(HGNC:""CLU""))")
increases(X,"act(p(HGNC:""AGER""))") <= increases("p(MGI:""Bace1"")",X)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases("p(HGNC:""ADAM10"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"a(CHEBI:""iron atom"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= decreases(X,"act(p(HGNC:""EIF2AK3""))")
increases("p(HGNC:""IL1B"")",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""))",Y)
increases(X,"act(p(FPLX:""ERK""))") <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",X)
increases(X,"bp(GO:""positive regulation of synaptic plasticity"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""BACE1"")",Y) <= increases("g(HGNC:""APP"",var(""G,717,C""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases(Y,"act(p(HGNC:""BDNF""))")
increases("p(HGNC:""BACE1"")",Y) <= increases(Y,"act(complex(FPLX:""PPP3""))")
increases("act(p(HGNC:""BACE1""))",Y) <= increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= decreases(X,"act(p(HGNC:""ERN1""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= directly_increases(Y,"rxn(reactants(a(CHEBI:""heme"")),products(a(CHEBI:""biliverdin""),a(CHEBI:""carbon monoxide""),a(CHEBI:""iron atom"")))")
increases("p(HGNC:""MAPT"",pmod(Ph))",Y) <= directly_decreases(Y,"bp(GO:""calcium ion homeostasis"")")
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= increases("p(HGNC:""C5"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"p(HGNC:""IL1RN"")")
increases(X,"p(HGNC:""BACE1"")") <= regulates(X,"p(HGNC:""BACE1"",pmod(Ac))")
increases("deg(p(HGNC:""APP""))",Y) <= increases("g(HGNC:""PSEN1"")",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases(Y,"act(p(HGNC:""NTRK2""))")
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"p(HGNC:""C5"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= regulates("p(HGNC:""ATXN1"")",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""wortmannin"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""MYC"",pmod(Ph))")
increases("p(HGNC:""PSEN1"")",Y) <= increases(Y,"p(HGNC:""BBC3"")")
increases("p(HGNC:""DYRK1A"")",Y) <= increases("act(p(HGNC:""PRKAR1A""),ma(kin))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""CACNG4"")",Y)
increases("p(HGNC:""DPP4"")",Y) <= increases("act(p(HGNC:""MMP2""),ma(pep))",Y)
increases("p(HGNC:""APP"")",Y) <= decreases(Y,"bp(GO:""positive regulation of synaptic plasticity"")")
increases(X,"bp(GO:""microglial cell activation"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(MGI:""Bace1"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("p(HGNC:""APOE"",var(""R,132,S""))",Y)
increases(X,"p(HGNC:""PLAUR"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""ADAM17""))",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"g(HGNC:""BACE1"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"act(p(HGNC:""MSR1""))")
increases(X,"a(CHEBI:""glutamate(1-)"")") <= regulates(X,"p(HGNC:""APP"",frag(""672_713""))")
increases(X,"p(HGNC:""NFKB2"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases(X,"p(HGNC:""APP"")") <= decreases("a(CHEBI:""curcumin"")",X)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"bp(GO:""regulation of inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity"")")
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= decreases("p(HGNC:""INS"")",X)
increases("a(MESH:""Astrocytes"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"bp(GO:""mitochondrial calcium ion homeostasis"")")
increases("complex(p(HGNC:""ACHE""),p(HGNC:""APP"",frag(""672_713"")))",Y) <= decreases(Y,"p(MGI:""Pparg"")")
increases(X,"a(CHEBI:""calcium(2+)"")") <= increases("deg(p(HGNC:""APP""))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= regulates("p(MGI:""Runx1"")",Y)
increases("deg(p(HGNC:""APP""))",Y) <= increases(Y,"act(p(HGNC:""CASR""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("act(p(HGNC:""MSR1""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"bp(GO:""lipid oxidation"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= decreases(X,"bp(GO:""response to unfolded protein"")")
increases(X,"act(p(HGNC:""AGER""))") <= decreases(X,"a(CHEBI:""ATP"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"p(HGNC:""SYP"")")
increases("p(HGNC:""APP"")",Y) <= increases(Y,"rxn(reactants(p(HGNC:""CDK5R1"")),products(p(CONSO:""CDK5R1 p25"")))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(FPLX:""HSPA"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""HDAC2"")",Y)
increases("a(CHEBI:""monosodium glutamate"")",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("a(CHEBI:""monosodium glutamate"")",Y)
increases("p(HGNC:""CCR2"")",Y) <= increases("p(HGNC:""S100A9"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""glutamate(2-)"")",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= decreases("a(CHEBI:""quetiapine"")",X)
increases("p(HGNC:""APP"")",Y) <= increases("a(CHEBI:""ceramide"")",Y)
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= decreases("a(MESH:""alpha-iso-cubebene"")",X)
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"bp(GO:""mitochondrial calcium ion homeostasis"")")
increases("p(HGNC:""PSEN1"")",Y) <= decreases("p(HGNC:""PRNP"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases("p(HGNC:""NFE2L2"")",X)
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"a(CHEBI:""ATP"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases(X,"bp(GO:""regulation of catalytic activity"")")
increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases(X,"p(HGNC:""PLAUR"")") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"path(MESH:""Gliosis"")") <= increases("deg(p(HGNC:""APP""))",X)
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""),p(HGNC:""LRP1""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= regulates("act(p(HGNC:""PSEN1""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases(Y,"p(MGI:""Pparg"")")
increases("p(HGNC:""APP"",var(""P,T,668""))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("p(HGNC:""APOE"")",Y) <= increases(Y,"complex(p(HGNC:""APOE""),p(HGNC:""APP"",frag(""672_713"")))")
increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y) <= decreases("bp(GO:""regulation of cAMP-dependent protein kinase activity"")",Y)
increases("p(HGNC:""APP"")",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("act(p(HGNC:""QPCT""),ma(pep))",Y) <= increases("act(p(HGNC:""BACE1""))",Y)
increases("p(HGNC:""CTSD"")",Y) <= directly_increases("act(p(HGNC:""BACE1""),ma(pep))",Y)
increases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("a(CHEBI:""ceramide"")",X)
increases("p(HGNC:""AGER"")",Y) <= increases("p(HGNC:""S100A9"")",Y)
increases("p(HGNC:""ACHE"")",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("deg(p(HGNC:""APP""))",Y) <= increases("a(CHEBI:""monosodium glutamate"")",Y)
increases(X,"act(p(HGNC:""AGER""))") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"p(HGNC:""BACE1"")") <= decreases(X,"a(CHEBI:""ATP"")")
increases(X,"p(HGNC:""APP"")") <= increases(X,"p(HGNC:""NFKB1"")")
increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""))",Y) <= decreases(Y,"bp(GO:""regulation of synaptic activity"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""Amylin"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""ADAM10""))",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"r(HGNC:""BACE1"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"a(CHEBI:""nitric oxide"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("bp(GO:""Wnt signaling pathway, planar cell polarity pathway"")",X)
increases(X,"path(CONSO:""neuroinflammation"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases("p(HGNC:""NFKB1"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"bp(GO:""neuron apoptotic process"")") <= increases("p(HGNC:""BACE1"")",X)
increases(X,"bp(GO:""positive regulation of synaptic plasticity"")") <= increases("p(HGNC:""BACE1"")",X)
increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y) <= decreases("a(CHEBI:""glimepiride"")",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases("composite(p(HGNC:""NOS3""),p(HGNC:""PIN1""))",Y)
increases(X,"p(HGNC:""DKK1"")") <= increases("p(HGNC:""BACE1"")",X)
increases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"act(p(HGNC:""GSK3A""))")
increases(X,"a(CHEBI:""reactive oxygen species"")") <= increases("p(HGNC:""BACE1"")",X)
increases("deg(p(HGNC:""APP""))",Y) <= increases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y)
increases(X,"act(p(HGNC:""CASR""))") <= increases("p(HGNC:""BACE1"")",X)
increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y) <= is_a(Y,"a(CHEBI:""amyloid-beta"")")
increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("complex(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""HSD17B10""))",Y)
increases("p(HGNC:""APP"")",Y) <= decreases("composite(p(HGNC:""NOS3""),p(HGNC:""PIN1""))",Y)
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= is_a(Y,"a(CHEBI:""amyloid-beta"")")
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""ACHE"")",Y)
increases("a(CHEBI:""amyloid-beta"")",Y) <= increases("complex(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""HSD17B10""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("p(HGNC:""ACHE"")",Y)
increases("p(HGNC:""BACE1"")",Y) <= decreases(Y,"bp(GO:""electron transport chain"")")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(HGNC:""PSEN2"",var(""N,141,I""))",X)
increases("p(HGNC:""BACE1"")",Y) <= increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"p(HGNC:""CCL2"")")
increases(X,"p(HGNC:""BACE1"")") <= increases("p(HGNC:""SOS1"")",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""SCARB1"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= regulates(X,"p(HGNC:""MAPT"",pmod(Ph))")
increases("p(HGNC:""PSEN1"")",Y) <= decreases(Y,"bp(GO:""electron transport chain"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"path(MESH:""Neurogenic Inflammation"")")
increases("p(MGI:""Bace1"")",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases(Y,"bp(GO:""regulation of synaptic plasticity"")")
increases("p(HGNC:""PSEN1"")",Y) <= increases("act(p(HGNC:""PSEN1""))",Y)
increases("p(HGNC:""APOE"")",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""lithium chloride"")",Y)
increases("p(HGNC:""APP"")",Y) <= increases("act(p(HGNC:""MAP3K5""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(MGI:""Ifng"")",X)
increases(X,"deg(p(HGNC:""APP""))") <= increases(X,"p(HGNC:""PSENEN"")")
increases("p(HGNC:""AGER"")",Y) <= decreases("composite(p(HGNC:""NOS3""),p(HGNC:""PIN1""))",Y)

/var/folders/ft/2nftg5q91n5dhpf5dtts4gkm0000gn/T/ipykernel_12191/2015677745.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_df = df[(df['Confidence']>=confidence_threshold) & (df_nad_100['Correct_Count']>correct_count_threshold)]

In [93]:
df_nad_increase_600 = extract_target_rules(df_nad_600, increase_ad_nodes, 'nad_600_rules.txt')
for i in df_nad_increase_600['Rule_Logic']:
    print(i)

Found 187 target rules
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""PSEN2"")",Y)
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= increases(X,"deg(p(HGNC:""APP"",frag(""672_711"")))")
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2B""))",X)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN3B""))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""GSK3B"",var(""Ph,S,9""))",Y)
increases(X,"deg(p(HGNC:""APP""))") <= decreases("act(p(HGNC:""GRIN2C""))",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""A2M"")",X)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("p(HGNC:""ABCA2"")",X)
increases(X,"p(HGNC:""APP"")") <= decreases("a(CHEBI:""thyroid hormone"")",X)
increases("p(HGNC:""APP"",var(""P,T,668""))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""BACE1"")",Y) <= increases(Y,"act(p(HGNC:""MSR1""))")
increases("p(HGNC:""APP"")",Y) <= increases(Y,"act(complex(FPLX:""PPP3""))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"bp(GO:""vasoconstriction"")")
increases("p(HGNC:""MAPT"",pmod(Ph))",Y) <= increases("act(p(HGNC:""QPCT""),ma(pep))",Y)
increases(X,"p(HGNC:""DKK1"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("deg(p(HGNC:""APP""))",Y) <= increases(Y,"act(complex(FPLX:""PPP3""))")
increases("act(p(HGNC:""BACE1""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y)
increases(X,"a(CHEBI:""reactive oxygen species"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases("p(HGNC:""PLAT"")",Y) <= increases("act(p(HGNC:""MMP2""),ma(pep))",Y)
increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(MGI:""Bace1"")",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"act(p(HGNC:""BDNF""))")
increases("p(HGNC:""AGER"")",Y) <= increases("p(HGNC:""BLMH"")",Y)
increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y) <= decreases(Y,"bp(MESH:""Cerebrovascular Circulation"")")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""BACE2""),ma(pep))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("g(HGNC:""APP"",var(""G,275341,C""))",Y)
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"bp(MESH:""Long-Term Potentiation"")")
increases("a(CHEBI:""metformin"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"act(p(HGNC:""NTRK2""))")
increases("p(HGNC:""CRH"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases(Y,"bp(MESH:""Long-Term Potentiation"")")
increases("deg(p(HGNC:""APP""))",Y) <= increases("g(HGNC:""APP"",var(""G,275341,C""))",Y)
increases("p(HGNC:""APP"")",Y) <= decreases(Y,"bp(GO:""mitochondrial calcium ion homeostasis"")")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases(Y,"act(complex(FPLX:""PPP3""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""IL34"")",X)
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""CLU"")",X)
increases(X,"bp(GO:""neuron death"")") <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("g(HGNC:""APP"",var(""G,717,C""))",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("g(HGNC:""PSEN1"")",Y)
increases("a(CHEBI:""metformin"")",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("complex(p(HGNC:""ACHE""),p(HGNC:""APP"",frag(""672_713"")))",Y)
increases("g(HGNC:""APP"",var(""G,717,C""))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("complex(p(HGNC:""APP"",var(""P,Y"")),p(HGNC:""GRB2""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y)
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""EIF2A"",pmod(Ph))",Y)
increases("p(HGNC:""APOE"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("act(p(HGNC:""GSK3B""))",Y) <= decreases(Y,"complex(p(HGNC:""CTNNB1""),p(HGNC:""PSEN1""))")
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases(Y,"act(p(HGNC:""BDNF""))")
increases("p(HGNC:""APP"")",Y) <= increases("p(HGNC:""APP"",frag(""740_770""))",Y)
increases("act(p(HGNC:""MMP2""),ma(pep))",Y) <= increases("p(HGNC:""DPP4"")",Y)
increases("a(CHEBI:""lead(0)"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""APP"")",Y) <= decreases("p(HGNC:""A2M"")",Y)
increases("p(HGNC:""PSEN2"",var(""N,141,I""))",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases("p(HGNC:""A2M"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""dipyridamole"")",Y)
increases("p(HGNC:""ACHE"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("a(CHEBI:""metformin"")",Y) <= increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= regulates(X,"bp(GO:""MAPK cascade"")")
increases("complex(p(HGNC:""APP"",var(""P,Y"")),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases("p(HGNC:""PRNP"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("complex(p(HGNC:""TNFRSF12A""),p(HGNC:""TNFRSF25""))",Y)
increases(X,"act(p(HGNC:""AGER""))") <= increases("p(MGI:""Bace1"")",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""CACNG1"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"act(complex(FPLX:""PPP3""))")
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= decreases(Y,"bp(MESH:""Cerebrovascular Circulation"")")
increases("act(p(HGNC:""BACE1""))",Y) <= increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases(Y,"act(p(HGNC:""NTRK2""))")
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"p(HGNC:""C5"")")
increases("p(HGNC:""PSEN1"")",Y) <= increases(Y,"act(p(HGNC:""MSR1""))")
increases("deg(p(HGNC:""APP""))",Y) <= increases("p(MGI:""Bace1"")",Y)
increases("complex(p(HGNC:""APP"",var(""P,Y"")),p(HGNC:""SHC2""))",Y) <= increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y)
increases("a(CHEBI:""monosodium glutamate"")",Y) <= decreases("complex(p(HGNC:""APBA1""),p(HGNC:""APP""))",Y)
increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y) <= directly_decreases(Y,"bp(GO:""calcium ion homeostasis"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(FPLX:""ERK"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("p(MGI:""Bace1"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("g(HGNC:""PSEN1"")",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""APPBP2"")",Y)
increases("complex(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""HSD17B10""))",Y) <= decreases("a(MESH:""Antioxidants"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""GSK3B"",pmod(Ph))")
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"act(p(HGNC:""BDNF""))")
increases("a(CHEBI:""nefiracetam"")",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases("a(CHEBI:""donepezil"")",Y) <= regulates(Y,"p(HGNC:""APP"",frag(""672_713""))")
increases(X,"p(HGNC:""NFKB2"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases("a(MESH:""Astrocytes"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"p(HGNC:""BACE1"")") <= decreases("a(CHEBI:""dorsomorphin"")",X)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"act(p(HGNC:""BACE1""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"bp(GO:""mitochondrial calcium ion homeostasis"")")
increases(X,"p(HGNC:""BACE1"")") <= decreases("a(CHEBI:""paroxetine"")",X)
increases("act(p(HGNC:""BACE1""))",Y) <= decreases("p(HGNC:""APBA1"")",Y)
increases("p(HGNC:""S100A9"")",Y) <= increases("p(HGNC:""CCR2"")",Y)
increases(X,"a(CHEBI:""nitric oxide"")") <= increases("deg(p(HGNC:""APP""))",X)
increases("p(HGNC:""APP"")",Y) <= decreases("path(MESH:""Inflammation"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= decreases(X,"bp(GO:""mitochondrial calcium ion homeostasis"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"bp(GO:""lipid oxidation"")")
increases(X,"act(p(HGNC:""GSK3B""))") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"p(HGNC:""CCL3"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""F2"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases(X,"p(HGNC:""SYP"")")
increases("p(HGNC:""BACE1"")",Y) <= decreases("p(HGNC:""PRNP"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= decreases(Y,"a(CHEBI:""ATP"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(FPLX:""HSPA"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"p(HGNC:""CCL5"")")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("a(CHEBI:""monosodium glutamate"")",X)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("a(CHEBI:""monosodium glutamate"")",Y)
increases("complex(p(HGNC:""APP""),p(HGNC:""DAB2""))",Y) <= decreases("a(CHEBI:""(S)-S-adenosyl-L-methionine"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""glutamate(2-)"")",Y)
increases("a(CHEBI:""lead(0)"")",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases(Y,"bp(GO:""regulation of synaptic activity"")")
increases("p(HGNC:""APP"")",Y) <= increases("a(CHEBI:""ceramide"")",Y)
increases("p(HGNC:""APP"")",Y) <= decreases(Y,"sec(p(HGNC:""BDNF""))")
increases("p(HGNC:""BACE1"")",Y) <= increases(Y,"p(HGNC:""PLAUR"")")
increases(X,"p(HGNC:""BACE1"")") <= increases("p(HGNC:""NFE2L2"")",X)
increases(X,"p(HGNC:""DKK1"")") <= increases("deg(p(HGNC:""APP""))",X)
increases("act(p(HGNC:""ADAM10""),ma(pep))",Y) <= directly_increases("act(p(HGNC:""BACE1""),ma(pep))",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("a(CHEBI:""ceramide"")",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("p(HGNC:""CASP1"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases(Y,"p(HGNC:""PLAUR"")")
increases("p(HGNC:""PSEN1"",var(""E,280,A""))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= increases("act(p(HGNC:""BACE1""))",Y)
increases("act(p(HGNC:""BACE1""))",Y) <= decreases("bp(GO:""regulation of cAMP-dependent protein kinase activity"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("deg(p(HGNC:""APP""))",X)
increases("act(complex(FPLX:""Gamma_secretase""),ma(pep))",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""),p(HGNC:""LRP1""))",Y)
increases(X,"p(HGNC:""APP"")") <= increases("complex(p(HGNC:""DOCK3""),p(HGNC:""MAP3K5""),p(HGNC:""RAC1""))",X)
increases(X,"a(CHEBI:""reactive oxygen species"")") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"deg(p(HGNC:""APP"",frag(""672_713"")))") <= increases(X,"bp(GO:""chemokine biosynthetic process"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("bp(GO:""cell cycle"")",Y)
increases("p(HGNC:""APP"")",Y) <= decreases(Y,"bp(GO:""electron transport chain"")")
increases("p(HGNC:""APP"")",Y) <= increases(Y,"bp(GO:""neurogenesis"")")
increases("g(HGNC:""APP"",var(""G,717,C""))",Y) <= increases("deg(p(HGNC:""APP""))",Y)
increases(X,"bp(GO:""positive regulation of neuron apoptotic process"")") <= increases("act(p(HGNC:""PSEN1""))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"path(MESH:""Neurodegenerative Diseases"")")
increases("deg(p(HGNC:""APP""))",Y) <= increases("a(CHEBI:""monosodium glutamate"")",Y)
increases(X,"act(p(HGNC:""AGER""))") <= increases("deg(p(HGNC:""APP""))",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""FASLG"")")
increases(X,"p(HGNC:""BACE1"")") <= decreases(X,"a(CHEBI:""ATP"")")
increases("p(HGNC:""APP"")",Y) <= decreases("p(HGNC:""PTPA"")",Y)
increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""))",Y) <= decreases(Y,"bp(GO:""regulation of synaptic activity"")")
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= decreases("bp(GO:""regulation of cAMP-dependent protein kinase activity"")",Y)
increases(X,"bp(GO:""neuron death"")") <= increases("p(HGNC:""S100A9"")",X)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("complex(p(HGNC:""APBB1""),p(HGNC:""APP""),p(HGNC:""LRP1""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""rutin"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"act(p(HGNC:""AGER""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"p(HGNC:""CTNNB1"",pmod(Ph))")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases("a(CHEBI:""Amylin"")",Y)
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("act(p(HGNC:""ADAM10""))",Y)
increases(X,"act(p(HGNC:""AGER""))") <= increases(X,"p(HGNC:""DKK1"")")
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("act(p(FPLX:""PRKAC""),ma(kin))",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("p(HGNC:""PPARG"")",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases(X,"complex(GO:""neurofibrillary tangle"")")
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CHEBI:""vitamin E"")",Y)
increases("p(HGNC:""PSEN1"")",Y) <= increases("p(HGNC:""APP"",var(""P,T,668""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("composite(p(HGNC:""NOS3""),p(HGNC:""PIN1""))",X)
increases(X,"path(CONSO:""neuroinflammation"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases("p(HGNC:""AGER"")",Y) <= increases(Y,"path(MESH:""Neurogenic Inflammation"")")
increases("p(HGNC:""NFKB1"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases(X,"act(p(HGNC:""CASR""))") <= increases(X,"complex(p(HGNC:""APOE""),p(HGNC:""APP"",frag(""672_713"")))")
increases(X,"bp(GO:""positive regulation of synaptic plasticity"")") <= increases("p(HGNC:""BACE1"")",X)
increases("p(HGNC:""PSEN1"")",Y) <= increases("a(CHEBI:""iron(2+)"")",Y)
increases("p(HGNC:""IFNG"")",Y) <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",Y)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= increases(Y,"act(p(HGNC:""GSK3A""))")
increases("g(HGNC:""APP"",var(""G,717,C""))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("deg(p(HGNC:""APP""))",Y) <= decreases(Y,"bp(GO:""electron transport chain"")")
increases(X,"bp(GO:""neuron apoptotic process"")") <= increases("composite(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""C1QBP""))",X)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("p(MGI:""Ifng"")",X)
increases("tloc(p(HGNC:""APP""),fromLoc(MESH:""Endosomes""),toLoc(MESH:""trans-Golgi Network""))",Y) <= is_a(Y,"a(CHEBI:""amyloid-beta"")")
increases("a(CHEBI:""okadaic acid"")",Y) <= increases("complex(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""HSD17B10""))",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases(X,"bp(GO:""neurogenesis"")")
increases("act(p(HGNC:""BACE1""),ma(pep))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases(X,"p(HGNC:""BACE1"")") <= increases("p(HGNC:""RELA"")",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(HGNC:""PSEN2"",var(""N,141,I""))",X)
increases(X,"act(p(HGNC:""AGER""))") <= increases("p(HGNC:""PSEN1"",var(""E,280,A""))",X)
increases("complex(p(HGNC:""APP"",frag(""672_713"")),p(HGNC:""HSD17B10""))",Y) <= increases("a(CHEBI:""amyloid-beta polypeptide 42"")",Y)
increases(X,"path(MESH:""Gliosis"")") <= increases("p(HGNC:""BACE1"")",X)
increases("p(HGNC:""APP"",frag(""672_713""))",Y) <= decreases("a(CONSO:""Amylin Antagonist AC253"")",Y)
increases("p(HGNC:""PSEN1"")",Y) <= decreases(Y,"bp(GO:""electron transport chain"")")
increases("complex(p(HGNC:""APP""),p(HGNC:""GRB2""),p(HGNC:""SHC2""))",Y) <= increases("complex(p(HGNC:""APP"",var(""P,Y"")),p(HGNC:""SHC2""))",Y)
increases("p(MGI:""Bace1"")",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases(X,"p(HGNC:""APP"")") <= increases(X,"tloc(a(CHEBI:""calcium(2+)""),fromLoc(MESH:""Endoplasmic Reticulum""),toLoc(MESH:""Cytoplasm""))")
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(HGNC:""BACE1"")",X)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= decreases("p(HGNC:""LEP"")",X)
increases("p(HGNC:""APOE"",var(""R,132,S""))",Y) <= increases("p(HGNC:""BACE1"")",Y)
increases("p(HGNC:""APP"")",Y) <= increases("act(p(HGNC:""MAP3K5""))",Y)
increases(X,"p(HGNC:""MAPT"",pmod(Ph))") <= increases("p(MGI:""Ifng"")",X)
increases("p(HGNC:""AGER"")",Y) <= decreases("composite(p(HGNC:""NOS3""),p(HGNC:""PIN1""))",Y)
increases(X,"p(HGNC:""APP"",frag(""672_713""))") <= increases("composite(p(HGNC:""IFNG""),p(HGNC:""TNF""))",X)

/var/folders/ft/2nftg5q91n5dhpf5dtts4gkm0000gn/T/ipykernel_12191/2015677745.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_df = df[(df['Confidence']>=confidence_threshold) & (df_nad_100['Correct_Count']>correct_count_threshold)]

check if rule-body's end node matches with ad-linked-nodes

In [84]:
def extract_and_match(row_string, match_list):
    # to find the part between the first comma and the ') <='
    pattern = r',\s*(.+)\)\s*<='
    match = re.search(pattern, row_string)
    
    if match:
        extracted = match.group(1)
        #print(extracted)
        # Normalize the string: change "" to " to match your list format
        normalized = extracted.replace('""', '"')
        print(normalized)
        
        if normalized in match_list:
            return True
    return False

# Filtering your dataframe
# Assuming 'Rule' is the column name
filtered_df = df_nad_100[df_nad_100['Rule_Logic'].apply(lambda x: extract_and_match(str(x), increase_ad_nodes))]

# Display results
print(filtered_df)

p(HGNC:"PRKCA"))",Y
"a(CHEBI:"glutamate(1-)")"
Y
Y
Y
Y
"a(CHEBI:"glutamate(1-)")"
p(HGNC:"PRKCA"))",Y
Y
Y
"p(HGNC:"MAPT",var("P,T,205"))"
"p(HGNC:"APP",frag("672_713"))"
ma(kin))",Y
"p(HGNC:"MAPT",var("P,S,202"))"
"deg(p(HGNC:"APP",frag("672_713")))"
"p(HGNC:"MAPT",var("P,S,202"))"
Y
"p(HGNC:"MAPT",var("P,T,205"))"
"act(p(FPLX:"ERK"))"
"act(p(HGNC:"CHRNA5"))"
"act(p(HGNC:"CHRNA2"))"
"act(p(HGNC:"CHRNA2"))"
"act(p(FPLX:"ERK"))"
"act(p(HGNC:"CHRNB2"))"
Y
a(MESH:"Pituitary Gland")))",Y
"act(p(HGNC:"CHRNA10"))"
"act(p(HGNC:"CHRNA3"))"
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA10"))"
"act(p(HGNC:"CHRNA4"))"
"p(HGNC:"MAPT",var("P,S,396"))"
"act(p(HGNC:"CHRNB3"))"
Y
"act(p(HGNC:"CHRNB2"))"
Y
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"PDPK1"))"
"act(p(HGNC:"CHRNB3"))"
"p(HGNC:"SOS1")"
Y
"act(p(HGNC:"CHRNA5"))"
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNA3"))"
Y
"act(p(HGNC:"CHRNA2"))"
Y
"act(p(HGNC:"CHRNA6"))"
Y
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNA6"))"
"p(HGNC:"SOS2")"
"act(p(HGNC:"CHRNA2"))"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNA2"))"
Y
"act(p(HGNC:"CHRNA5"))"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNA4"))"
Y
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA4"))"
"act(p(HGNC:"CHRNA10"))"
"a(MESH:"Chemokines")"
"act(p(HGNC:"CHRNA3"))"
Y
"act(p(HGNC:"CHRNB2"))"
"act(p(FPLX:"ERK"))"
Y
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNB3"))"
Y
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA10"))"
"bp(GO:"cognition")"
Y
"act(p(HGNC:"CHRNA3"))"
"act(p(HGNC:"CHRNA3"))"
"act(p(HGNC:"CHRNA4"))"
"act(p(HGNC:"CHRNB3"))"
Y
"act(p(HGNC:"CHRNA5"))"
Y
Y
var("N,141,I"))",Y
"act(p(HGNC:"CHRNB3"))"
"act(p(HGNC:"CHRNA5"))"
"bp(GO:"cognition")"
Y
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA10"))"
Y
"act(p(HGNC:"CHRNA10"))"
"act(p(HGNC:"CHRNA4"))"
"path(CONSO:"neuroinflammation")"
ma(kin))",Y
"bp(GO:"cognition")"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNA5"))"
"act(p(HGNC:"CHRNA2"))"
"act(p(HGNC:"CHRNB3"))"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNA4"))"
"act(p(HGNC:"CHRNA6"))"
"p(HGNC:"APP",var("P,T,668"))"
"act(p(HGNC:"CHRNA3"))"
Y
"act(p(HGNC:"CHRNA4"))"
"p(HGNC:"MAPT",var("P,S,262"))"
"act(p(HGNC:"CHRNA10"))"
Y
Y
"act(p(HGNC:"CHRNA4"))"
"act(p(HGNC:"CHRNA2"))"
"act(p(HGNC:"CHRNB3"))"
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA5"))"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNB3"))"
"act(p(HGNC:"CHRNA3"))"
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNA10"))"
"act(p(HGNC:"CHRNA3"))"
"act(p(HGNC:"CHRNA2"))"
"a(MESH:"Interleukins")"
"act(p(FPLX:"JNK"))"
Y
"act(p(HGNC:"CHRNA5"))"
Y
Y
"act(p(HGNC:"CHRNA9"))"
var("E,280,A"))",Y
"act(p(HGNC:"CHRNB3"))"
"act(p(HGNC:"CHRNA3"))"
"deg(p(HGNC:"APP"))"
"bp(GO:"apoptotic process")"
"act(p(HGNC:"CHRNA9"))"
"act(p(HGNC:"CHRNA5"))"
Y
var("P,T,668"))",Y
"bp(GO:"neuron death")"
Y
"a(CHEBI:"nitric oxide")"
frag("672_713")),p(HGNC:"C1QBP"))",Y
ma(pep))",Y
"act(p(HGNC:"MAPK1"))"
Y
Y
"act(a(MESH:"Hypothalamus"))"
"deg(p(HGNC:"APP"))"
"act(p(HGNC:"CHRNA10"))"
"act(p(HGNC:"CHRNA4"))"
Y
"a(CHEBI:"calcium(2+)")"
"act(p(HGNC:"CHRNB2"))"
"act(p(HGNC:"CHRNB3"))"
"a(CHEBI:"calcium(2+)")"
"a(CHEBI:"amyloid-beta")"
"act(p(HGNC:"CHRNA2"))"
Y
Y
"bp(GO:"negative regulation of neuron apoptotic process")"
Y
Y
"act(a(CHEBI:"donepezil"))"
"act(a(CHEBI:"donepezil"))"
Y
Y
Y
"bp(GO:"apoptotic process")"
"act(a(CHEBI:"galanthamine"))"
"act(p(HGNC:"CHRNA6"))"
"act(p(HGNC:"CHRNA6"))"
"a(CHEBI:"amyloid-beta")"
"p(HGNC:"APP",var("P,T,668"))"
"deg(p(HGNC:"APP"))"
"a(CHEBI:"amyloid-beta")"
frag("672_713"))",Y
Y
"a(CHEBI:"amyloid-beta")"
"act(p(HGNC:"CHRNA4"))"
Y
Y
p(HGNC:"PDPK1"),p(HGNC:"PIK3R5")))",Y
var("P,T")))",Y
"a(CHEBI:"amyloid-beta")"
Y
Y
"act(a(MESH:"Pituitary Gland"))"
"act(p(HGNC:"MAPK3"))"
"p(HGNC:"IL1B")"
"a(CHEBI:"amyloid-beta")"
"bp(GO:"metabolic process")"
Y
Y
"bp(GO:"metabolic process")"
"act(p(HGNC:"MAPK1"))"
"deg(a(CHEBI:"glyoxal"))"
frag("672_713")),p(HGNC:"C1QBP"))",Y
Y
Y
"act(p(HGNC:"CHRNA2"))"
"bp(GO:"metabolic process")"
"act(a(CHEBI:"galanthamine"))"
"bp(GO:"neuron death")"
Y
Y
"a(CHEBI:"amyloid-beta")"
p(HGNC:"PDPK1"),p(HGNC:"PIK3R5")))",Y
"act(p(HGNC:"MAPK3"))"
frag("672_713"))",Y
Y
Y
"deg(p(HGNC:"APP"))"
"a(CHEBI:"amyloid-beta")"
cholinergic")",Y
"deg(p(HGNC:"APP"))"
Y
Y
"act(a(CHEBI:"tacrine"))"
Y
Y
Y
"p(HGNC:"CCR2")"
Y
Y
"p(HGNC:"CXCL8")"
Y
frag("672_713")),p(HGNC:"C1QBP"))",Y
p(HGNC:"GRB2"))",Y
Y
"p(HGNC:"APP",var("P,T,654"))"
Y
"act(a(CHEBI:"tacrine"))"
Y
"deg(p(HGNC:"APP"))"
"deg(a(CHEBI:"methylglyoxal"))"
"deg(p(HGNC:"APP"))"
"act(p(HGNC:"CHRNA3"))"
Y
"p(HGNC:"CXCL10")"
"act(p(HGNC:"CHRNA9"))"
Y
"p(HGNC:"CXCL8")"
"act(p(HGNC:"CHRNA5"))"
Y
Y
"p(HGNC:"IL1B")"
"bp(GO:"glucose metabolic process")"
Y
cholinergic")",Y
p(HGNC:"SHC2"))",Y
Y
Y
"act(p(HGNC:"CHRNA10"))"
Y
Y
"act(p(HGNC:"CHRNB2"))"
Y
"g(HGNC:"NAB2")"
"bp(GO:"microglial cell activation")"
"p(HGNC:"MAPT",pmod(Ph))"
Y
Y
"act(p(HGNC:"EIF2AK3"))"
"g(HGNC:"EGR1")"
"a(CHEBI:"amyloid-beta")"
Y
p(HGNC:"TNF"))",Y
"p(HGNC:"APP")"
Y
Y
"p(HGNC:"PSEN1")"
"p(HGNC:"APP",frag("672_713"))"
"p(HGNC:"APP")"
"p(HGNC:"DKK1")"
var("P,T,668"))",Y
Y
Y
"deg(p(HGNC:"APP"))"
"bp(GO:"apoptotic process")"
"a(CHEBI:"nitric oxide")"
Y
var("N,141,I"))",Y
"bp(GO:"phagocytosis")"
Y
Y
"bp(GO:"microglial cell activation")"
Y
p(HGNC:"APP"),p(HGNC:"LRP1"))",Y
Y
Y
"bp(GO:"apoptotic process")"
Y
"bp(GO:"neurogenesis")"
Y
Y
"p(HGNC:"BCL2L11")"
"a(CHEBI:"reactive oxygen species")"
frag("672_713"))",Y
"p(MGI:"Il1b")"
var("R,132,S"))",Y
"act(p(HGNC:"MSR1"))"
Y
"bp(GO:"cognition")"
"bp(GO:"inflammatory response")"
Y
frag("672_713"))",Y
Y
"bp(GO:"neuron apoptotic process")"
Y
"p(HGNC:"LAMTOR3")"
Y
Y
Y
p(HGNC:"DAB2"))",Y
"bp(GO:"neuron death")"
Y
Y
Y
Y
"bp(GO:"positive regulation of synaptic plasticity")"
Y
"act(complex(FPLX:"PPP3"))"
Y
Y
"bp(GO:"apoptotic process")"
Y
ma(pep))",Y
pmod(Ph))",Y
"p(HGNC:"DKK1")"
Y
"act(p(HGNC:"MSR1"))"
"p(HGNC:"SOS1")"
"bp(GO:"response to endoplasmic reticulum stress")"
var("E,280,A"))",Y
Y
Y
"a(CHEBI:"amyloid-beta")"
Y
"p(HGNC:"IL12B")"
var("K,595,N"))",Y
pmod(Ph))",Y
"p(HGNC:"APP")"
Y
Y
Y
"bp(GO:"regulation of inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity")"
"deg(a(CHEBI:"heme"))"
"bp(GO:"regulation of inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity")"
Y
Y
"p(HGNC:"HINFP",var("A,K,5"))"
"a(CHEBI:"calcium(2+)")"
Y
"p(HGNC:"RAF1")"
"act(complex(FPLX:"PPP3"))"
Y
Y
Y
"bp(GO:"neurogenesis")"
"act(p(HGNC:"MSR1"))"
"path(CONSO:"neuroinflammation")"
Y
Y
"p(HGNC:"MAPT",var("P,T"))"
Y
"p(HGNC:"CTNNB1",pmod(Ph))"
Y
"a(CHEBI:"amyloid-beta")"
Y
var("P,T,668"))",Y
"p(HGNC:"IL1B")"
"bp(GO:"neuron death")"
"a(CHEBI:"amyloid-beta")"
Y
Y
"bp(GO:"neuron apoptotic process")"
"complex(GO:"plasma lipoprotein particle")"
Y
Y
Y
Y
"bp(GO:"inflammatory response")"
"a(CHEBI:"nitric oxide")"
"a(CHEBI:"reactive oxygen species")"
Y
pmod(Ac))",Y
Y
Y
Y
var("E,280,A"))",Y
Y
Y
Y
Y
Y
var("P,Y")),p(HGNC:"GRB2"))",Y
"a(CHEBI:"reactive oxygen species")"
var("P,Y")),p(HGNC:"GRB2"),p(HGNC:"SHC2"))",Y
var("G,275341,C"))",Y
Y
"p(HGNC:"IRS2",var("P,T"))"
Y
"a(CHEBI:"nitric oxide")"
Y
Y
Y
"path(MESH:"Gliosis")"
"p(HGNC:"DKK1")"
Y
Y
Y
"p(HGNC:"BACE1")"
Y
ma(pep))",Y
"p(HGNC:"IL1B")"
"a(CHEBI:"amyloid-beta")"
Y
Y
Y
"bp(GO:"oxidative phosphorylation")"
Y
Y
"a(CHEBI:"amyloid-beta")"
Y
Y
"act(p(HGNC:"FOS"))"
Y
intracellular domain, conserved site")",Y
"p(HGNC:"TNF")"
"p(HGNC:"PLAUR")"
"a(CHEBI:"reactive oxygen species")"
Y
Y
var("G,717,C"))",Y
"bp(GO:"apoptotic process")"
ma(pep))",Y
"p(HGNC:"PLAUR")"
Y
Y
"act(p(HGNC:"MSR1"))"
Y
Y
"bp(GO:"inflammatory response")"
Y
Y
var("P,T,668"))",Y
Y
"p(HGNC:"MAPT",pmod(Ph))"
"p(HGNC:"CCL5")"
Y
"act(p(HGNC:"AGER"))"
Y
Y
cholinergic")",Y
"bp(GO:"cognition")"
Y
Y
"act(p(HGNCGENEFAMILY:"Mitogen-activated protein kinases"))"
Y
Y
p(HGNC:"SELP"))",Y
Y
Y
"act(p(HGNC:"MSR1"))"
"p(HGNC:"DPYSL2",pmod(Ph))"
Y
"p(HGNC:"MAPT",pmod(Ph))"
"p(HGNC:"APP",frag("672_713"))"
Y
var("N,141,I"))",Y
Y
"act(p(FPLX:"ERK"))"
Y
Y
Y
Y
"a(CHEBI:"reactive oxygen species")"
Y
Y
Y
"p(HGNC:"SOS2")"
Y
"path(MESH:"Gliosis")"
"path(MESH:"Gliosis")"
pmod(Ac))",Y
fromLoc(MESH:"Endosomes"),toLoc(MESH:"trans-Golgi Network"))",Y
Y
Y
Y
Y
Y
Y
Y
Y
Y
p(HGNC:"DAB2"))",Y
Y
pmod(Ph))",Y
Y
"a(CHEBI:"amyloid-beta")"
"bp(GO:"microglial cell activation")"
Y
"bp(GO:"neuron death")"
var("E,280,A"))",Y
Y
Y
"tloc(a(CHEBI:"calcium(2+)"),fromLoc(MESH:"Endoplasmic Reticulum"),toLoc(MESH:"Cytoplasm"))"
Y
"path(MESH:"Inflammation")"
"act(p(HGNC:"CASR"))"
Y
var("E,280,A"))",Y
"p(HGNC:"TNF")"
"act(p(HGNC:"MSR1"))"
Y
"p(HGNC:"TNF")"
"a(CHEBI:"amyloid-beta")"
Y
"p(HGNC:"PSENEN")"
Y
"a(CHEBI:"nitric oxide")"
Y
ma(pep))",Y
"p(HGNC:"CCL3")"
ma(pep))",Y
"p(HGNC:"MAPT",var("P,T,181"))"
Y
"bp(GO:"regulation of dendritic cell dendrite assembly")"
Y
"a(CHEBI:"amyloid-beta")"
Y
"bp(GO:"response to endoplasmic reticulum stress")"
Y
"deg(p(HGNC:"APP"))"
"a(CHEBI:"calcium(2+)")"
Y
Y
Y
"p(HGNC:"IL1B")"
"p(HGNC:"PLAUR")"
frag("672_713"))",Y
Y
Y
Y
"path(MESH:"Gliosis")"
"p(MGI:"Gfap")"
Y
p(HGNC:"SELP"))",Y
"p(HGNC:"MAPT",var("P,S,199"))"
"p(FPLX:"CREB",pmod(Ph))"
Y
"act(p(HGNC:"BACE1"),ma(pep))"
Y
"rxn(reactants(p(HGNC:"APP")),products(p(HGNC:"APP",frag("672_713"))))"
Y
var("P,T,668"))",Y
"act(p(HGNC:"GSK3B"))"
ma(pep))",Y
Y
"rxn(reactants(p(HGNC:"APP")),products(a(CHEBI:"amyloid-beta")))"
Y
Y
Y
var("E,280,A"))",Y
"r(HGNC:"BACE1")"
var("G,275341,C"))",Y
Y
var("N,141,I"))",Y
Y
"a(CHEBI:"reactive oxygen species")"
"p(HGNC:"APP")"
Y
"a(CHEBI:"calcium(2+)")"
"act(a(MESH:"Pituitary Gland"))"
Y
var("P,T,668"))",Y
Y
"p(HGNC:"IAPP")"
p(HGNC:"TNF"))",Y
"act(p(HGNC:"GSK3B"))"
Y
"p(HGNC:"MAPT",pmod(Ph,S,422))"
ma(pep))",Y
Y
"a(CHEBI:"amyloid-beta")"
Y
Y
"bp(GO:"neuron apoptotic process")"
Y
Y
"a(CHEBI:"calcium(2+)")"
var("P,T,668"))",Y
Y
"bp(GO:"regulation of ryanodine-sensitive calcium-release channel activity")"
var("K,595,N"))",Y
var("N,141,I"))",Y
Y
"bp(GO:"neuron apoptotic process")"
ma(pep))",Y
Y
Y
"bp(GO:"cell adhesion")"
var("E,280,A"))",Y
"bp(GO:"neuron death")"
"act(p(HGNC:"GSK3B"))"
Y
Y
Y
"bp(GO:"neuron apoptotic process")"
Y
Y
"p(HGNC:"CCL3")"
"path(MESH:"Gliosis")"
"bp(GO:"apoptotic process")"
Y
"act(p(HGNC:"AGER"))"
"bp(GO:"regulation of ryanodine-sensitive calcium-release channel activity")"
Y
"p(HGNC:"DPYSL2",pmod(Ph))"
pmod(Ph))",Y
Y
Y
"a(CHEBI:"reactive oxygen species")"
Y
Y
Y
"a(CHEBI:"calcium(2+)")"
"bp(GO:"positive regulation of synaptic plasticity")"
"act(a(MESH:"Hypothalamus"))"
"p(MGI:"Ptgs2")"
"a(CHEBI:"copper(1+)")"
Y
Y
"p(HGNC:"IL1B")"
"a(CHEBI:"reactive oxygen species")"
"p(HGNC:"BACE1")"
Y
Y
p(HGNC:"PECAM1"))",Y
Y
"a(CHEBI:"amyloid-beta")"
Y
Y
cholinergic")",Y
Y
Y
"tloc(a(CHEBI:"calcium(2+)"),fromLoc(MESH:"Endoplasmic Reticulum"),toLoc(MESH:"Cytoplasm"))"
Y
LDL"),p(HGNC:"APOB"))",Y
Y
"p(HGNC:"MAPT",pmod(Ph))"
var("G,717,C"))",Y
Y
fromLoc(MESH:"Endosomes"),toLoc(MESH:"trans-Golgi Network"))",Y
frag("672_713"))",Y
"act(p(HGNC:"GSK3B"))"
"deg(a(CHEBI:"glyoxal"))"
"bp(GO:"neuron apoptotic process")"
Y
"bp(GO:"neuron apoptotic process")"
"p(HGNC:"MAPT",var("P,T,231"))"
"tloc(a(CHEBI:"calcium(2+)"),fromLoc(MESH:"Endoplasmic Reticulum"),toLoc(MESH:"Cytoplasm"))"
Y
Y
Y
"p(MGI:"Hmox1")"
"p(HGNC:"MAPT",pmod(Ph))"
"act(p(FPLX:"ERK"))"
"a(CHEBI:"amyloid-beta")"
Y
Y
"bp(GO:"positive regulation of synaptic plasticity")"
Y
var("G,717,C"))",Y
Y
Y
"p(HGNC:"PLAUR")"
ma(kin))",Y
Y
Y
var("G,717,C"))",Y
p(HGNC:"ICAM1"))",Y
Y
"p(MGI:"Vim",pmod(GO:"protein oxidation"))"
Y
Y
Y
"a(CHEBI:"calcium(2+)")"
"path(MESH:"Gliosis")"
"act(complex(FPLX:"PPP3"))"
"a(CHEBI:"reactive oxygen species")"
Y
Y
Y
var("N,141,I"))",Y
"act(p(HGNC:"AGER"))"
"a(CHEBI:"amyloid-beta")"
"deg(p(HGNC:"CLSTN3"))"
"path(MESH:"Inflammation")"
"act(p(HGNC:"PRKCD"))"
"bp(GO:"positive regulation of neuron apoptotic process")"
Y
"act(p(HGNC:"MAPK1"))"
"p(HGNC:"PLAUR")"
Y
Y
"p(HGNC:"PLAUR")"
var("G,717,C"))",Y
"act(p(FPLX:"ERK"),ma(kin))"
Y
Y
Y
Y
"a(CHEBI:"amyloid-beta")"
Y
Y
Y
"bp(GO:"cognition")"
"bp(GO:"neuron death")"
"p(HGNC:"MAPT",pmod(Ph))"
Y
Y
Y
"bp(GO:"neuron death")"
"a(CHEBI:"amyloid-beta")"
var("G,275341,C"))",Y
Y
Y
Y
var("G,275341,C"))",Y
ma(kin))",Y
ma(pep))",Y
Y
"act(p(HGNC:"MSR1"))"
"p(HGNC:"IL1B")"
Y
Y
Y
Y
Y
Y
Y
p(HGNC:"ICAM2"))",Y
Y
Y
"act(p(HGNC:"GSK3B"))"
Y
"deg(p(HGNC:"APP"))"
Y
"bp(GO:"microglial cell activation")"
"deg(p(HGNC:"CLSTN2"))"
Y
ma(pep))",Y
var("N,141,I"))",Y
var("G,717,C"))",Y
Y
"path(MESH:"Inflammation")"
ma(pep))",Y
Y
var("P,T,668"))",Y
var("P,T,668"))",Y
"p(HGNC:"PLAUR")"
"a(CHEBI:"reactive oxygen species")"
"bp(GO:"response to endoplasmic reticulum stress")"
Y
"deg(p(HGNC:"CLSTN1"))"
"p(HGNC:"TLR4")"
Y
Y
var("P,Y")),p(HGNC:"GRB2"))",Y
Y
"bp(GO:"response to endoplasmic reticulum stress")"
"p(HGNC:"PLAUR")"
var("G,275341,C"))",Y
"bp(GO:"neuron development")"
Y
Y
Y
Y
Y
"p(HGNC:"IL1B")"
p(HGNC:"TNF"))",Y
Y
"act(p(HGNC:"ATF6"))"
Y
"a(CHEBI:"amyloid-beta")"
ma(pep))",Y
Y
Y
Y
"bp(GO:"neuron apoptotic process")"
var("G,275341,C"))",Y
Y
"p(HGNC:"RASGRF1")"
var("G,717,C"))",Y
"p(HGNC:"PLAUR")"
Y
"p(HGNC:"SOS1")"
Y
Y
"bp(GO:"cell adhesion")"
frag("672_713"))",Y
var("P,T,668"))",Y
ma(pep))",Y
Y
"p(HGNC:"IL1B")"
Y
"a(CHEBI:"iron atom")"
Y
"a(CHEBI:"amyloid-beta")"
"act(p(HGNC:"MSR1"))"
"bp(GO:"memory")"
Y
p(HGNC:"ICAM1"))",Y
ma(pep))",Y
"bp(GO:"ATP biosynthetic process")"
Y
pmod(Ph))",Y
Y
Y
p(HGNC:"TNFRSF25"))",Y
Y
"p(HGNC:"DKK1")"
Y
Y
Y
p(HGNC:"ICAM2"))",Y
"bp(GO:"neuron apoptotic process")"
Y
Y
Y
Y
"a(CHEBI:"3',5'-cyclic AMP")"
Y
Y
"bp(GO:"positive regulation of mitochondrial membrane potential")"
Y
Y
Y
Y
ma(pep))",Y
"bp(GO:"microglial cell activation")"
Y
ma(pep))",Y
"act(a(MESH:"Hypothalamus"))"
Y
Y
Y
"a(CHEBI:"calcium(2+)")"
"path(MESH:"Gliosis")"
Y
"p(HGNC:"MAPT",var("P,T,205"))"
Y
"complex(p(FPLX:"IRS"),p(HGNC:"GRB2"))"
frag("672_713"))",Y
Y
"bp(GO:"neuron apoptotic process")"
"p(HGNC:"APP",frag("672_713"))"
Y
Y
"bp(GO:"positive regulation of synaptic plasticity")"
"deg(p(HGNC:"APP"))"
"tloc(a(CHEBI:"calcium(2+)"),fromLoc(MESH:"Endoplasmic Reticulum"),toLoc(MESH:"Cytoplasm"))"
Y
"p(HGNC:"PSEN2")"
Y
Y
Y
"p(HGNC:"MAPT",pmod(Ph,S))"
Y
Y
Y
p(HGNC:"TNF"))",Y
Y
Y
Y
Y
"act(p(HGNC:"NGF"))"
cholinergic")",Y
"a(CHEBI:"amyloid-beta")"
"a(CHEBI:"amyloid-beta")"
Y
"bp(GO:"positive regulation of synaptic plasticity")"
"a(CHEBI:"amyloid-beta")"
p(HGNC:"PECAM1"))",Y
Y
"act(complex(FPLX:"PPP3"))"
Y
Y
"a(CHEBI:"calcium(2+)")"
Y
"bp(GO:"apoptotic process")"
Y
Y
"act(p(HGNC:"AGER"))"
pmod(Ph))",Y
Y
LDL"),p(HGNC:"APOB"))",Y
"deg(a(CHEBI:"methylglyoxal"))"
Y
"complex(GO:"neurofibrillary tangle")"
"bp(GO:"cognition")"
"bp(GO:"neuron death")"
Y
"bp(GO:"membrane lipid catabolic process")"
Y
ma(pep))",Y
"p(HGNC:"IL1B")"
Y
Y
"p(HGNC:"IL1B")"
Y
var("R,132,S"))",Y
"a(CHEBI:"nitric oxide")"
pmod(Glyco))",Y
Y
"p(CONSO:"sAPP-alpha")"
Y
Y
"p(HGNC:"C5")"
Y
frag("672_713"))",Y
fromLoc(MESH:"Endosomes"),toLoc(MESH:"trans-Golgi Network"))",Y
"act(p(HGNC:"CASR"))"
Y
"bp(GO:"apoptotic process")"
Y
p(HGNC:"APP"))",Y
Y
Y
"a(CHEBI:"reactive oxygen species")"
Y
Y
"act(p(HGNC:"GSK3B"))"
"bp(GO:"negative regulation of neuron apoptotic process")"
"a(CHEBI:"reactive oxygen species")"
"deg(p(HGNC:"APP"))"
"bp(GO:"central nervous system development")"
"bp(GO:"neuron death")"
"act(p(HGNC:"MAPK1"))"
Y
Y
p(HGNC:"TNF"))",Y
Y
ma(pep))",Y
"p(HGNC:"APP",pmod(Ph))"
Y
pmod(Ph))",Y
"p(HGNC:"MAPT",pmod(Ph))"
Y
"path(MESH:"Gliosis")"
Brain")",Y
frag("672_713"))",Y
Y
"bp(GO:"cognition")"
"a(CHEBI:"calcium(2+)")"
Y
Y
"p(HGNC:"APP",frag("672_713"))"
Y
Y
"bp(GO:"memory")"
"bp(GO:"neuron death")"
Y
Y
var("P,T,668"))",Y
"p(HGNC:"PSENEN")"
var("R,132,S"))",Y
p(HGNC:"SELP"))",Y
frag("672_713"))",Y
"path(MESH:"Inflammation")"
ma(pep))",Y
"bp(GO:"microglial cell activation")"
ma(pep))",Y
"p(FPLX:"AKT",pmod(Ph))"
var("G,275341,C"))",Y
"deg(p(HGNC:"APP"))"
p(HGNC:"ICAM2"))",Y
"p(HGNC:"MAPT",var("P,S,396"))"
Y
"bp(GO:"cognition")"
"bp(GO:"neuron death")"
"a(CHEBI:"amyloid-beta")"
"bp(GO:"inflammatory response")"
Y
var("P,Y")),p(HGNC:"GRB2"),p(HGNC:"SHC2"))",Y
"a(CHEBI:"amyloid-beta")"
"a(CHEBI:"calcium(2+)")"
cholinergic")",Y
"a(CHEBI:"amyloid-beta")"
"path(MESH:"Inflammation")"
"path(MESH:"Inflammation")"
"a(CHEBI:"amyloid-beta")"
"bp(GO:"apoptotic process")"
var("P,S,133"))",Y
var("N,141,I"))",Y
"bp(GO:"positive regulation of synaptic plasticity")"
"path(MESH:"Inflammation")"
Y
"act(complex(FPLX:"PPP3"))"
Y
Y
Y
Y
"p(HGNC:"PSENEN")"
frag("672_713"))",Y
"bp(GO:"neuron apoptotic process")"
Y
Y
var("N,141,I"))",Y
"bp(GO:"chronic inflammatory response")"
Y
Y
Y
Y
p(HGNC:"PECAM1"))",Y
Y
"a(CHEBI:"calcium(2+)")"
Y
Y
"bp(GO:"neuron apoptotic process")"
Y
Y
Y
"p(HGNC:"DPYSL2",pmod(Ph))"
"p(HGNC:"CXCL10")"
frag("672_713"))",Y
pmod(Ph))",Y
Y
"act(p(HGNC:"CASR"))"
Y
Y
"bp(GO:"regulation of ryanodine-sensitive calcium-release channel activity")"
"bp(GO:"cognition")"
frag("672_713"))",Y
"bp(GO:"apoptotic process")"
Y
ma(pep))",Y
Y
frag("672_713"))",Y
Y
"a(CHEBI:"amyloid-beta")"
Y
"p(HGNC:"IL1B")"
ma(pep))",Y
"rxn(reactants(p(HGNC:"CDK5R1")),products(p(CONSO:"CDK5R1 p25")))"
Y
Y
Y
Y
Y
"bp(GO:"neuron death")"
"a(CHEBI:"calcium(2+)")"
Y
"p(HGNC:"DKK1")"
var("P,T,668"))",Y
var("R,132,S"))",Y
"bp(GO:"microglial cell activation")"
"act(p(HGNC:"CASR"))"
Y
"path(MESH:"Gliosis")"
"deg(p(HGNC:"CLSTN2"))"
"bp(GO:"neuron apoptotic process")"
Y
"bp(GO:"apoptotic process")"
Y
frag("672_713"))",Y
Brain")",Y
Y
"a(CHEBI:"iron atom")"
"bp(GO:"apoptotic process")"
"bp(GO:"neuron apoptotic process")"
"bp(GO:"positive regulation of mitochondrial membrane potential")"
Y
"bp(GO:"ATP biosynthetic process")"
"p(HGNC:"DKK1")"
Y
"act(p(HGNC:"MAPK3"))"
Y
Y
"a(CHEBI:"nitric oxide")"
Y
Y
var("E,280,A"))",Y
Y
"p(HGNC:"IL1B")"
"bp(GO:"microglial cell activation")"
"act(p(HGNC:"AGER"))"
p(HGNC:"DAB2"))",Y
"a(CHEBI:"amyloid-beta")"
"path(MESH:"Inflammation")"
"act(p(HGNC:"CASR"))"
Y
"bp(GO:"neurogenesis")"
frag("672_713"))",Y
frag("672_713"))",Y
Y
"act(p(HGNC:"ERN1"))"
Y
Y
Y
Y
"sec(a(CHEBI:"amyloid-beta"))"
Y
"a(MESH:"Microglia")"
"a(CHEBI:"calcium(2+)")"
"p(HGNC:"APP",frag("672_713"))"
"a(CHEBI:"amyloid-beta")"
Y
"p(HGNC:"DPYSL2",pmod(Ph))"
Y
ma(pep))",Y
var("G,275341,C"))",Y
Y
"p(HGNC:"APP",frag("672_713"))"
"bp(GO:"apoptotic process")"
"bp(GO:"apoptotic process")"
"p(HGNC:"MAPT",pmod(Ph))"
"p(MGI:"Ngf")"
"p(HGNC:"MAPT",pmod(Ph))"
"act(p(HGNC:"MSR1"))"
Y
"a(CHEBI:"amyloid-beta")"
frag("672_713"))",Y
"bp(GO:"response to endoplasmic reticulum stress")"
frag("672_713"))",Y
Y
Y
Y
"act(p(HGNC:"GSK3B"))"
"a(CHEBI:"icosanoid")"
"act(p(HGNC:"GSK3B"))"
"act(p(HGNC:"CASP1"))"
Y
var("G,275341,C"))",Y
Y
Y
"act(p(FPLX:"ERK"))"
Y
LDL"),p(HGNC:"APOB"))",Y
Y
"act(p(HGNC:"AGER"))"
var("R,132,S"))",Y
"bp(GO:"positive regulation of synaptic plasticity")"
"act(p(HGNC:"ERN1"))"
"a(CHEBI:"amyloid-beta")"
Y
Brain")",Y
"a(CHEBI:"reactive oxygen species")"
Y
"bp(GO:"apoptotic process")"
ma(pep))",Y
Y
"bp(GO:"neuron development")"
Y
Y
Y
fromLoc(MESH:"Endosomes"),toLoc(MESH:"trans-Golgi Network"))",Y
Y
ma(pep))",Y
Y
Y
ma(pep))",Y
Y
Y
"act(a(MESH:"Pituitary Gland"))"
"path(MESH:"Inflammation")"
Y
Y
"p(HGNC:"IL1B")"
Y
frag("672_713"))",Y
"a(CHEBI:"calcium(2+)")"
ma(kin))",Y
"bp(GO:"neuron apoptotic process")"
"p(HGNC:"APP",frag("672_713"))"
Y
cholinergic")",Y
Y
ma(kin))",Y
"bp(GO:"neuron apoptotic process")"
Y
"complex(p(HGNC:"GAB1"),p(HGNC:"GRB2"))"
"bp(GO:"memory")"
ma(pep))",Y
Y
pmod(Ph))",Y
var("P,T,668"))",Y
Y
Y
"bp(GO:"positive regulation of synaptic plasticity")"
frag("672_713"))",Y
ma(pep))",Y
Y
"act(p(HGNC:"EIF2AK3"))"
Y
Y
"act(complex(FPLX:"PPP3"))"
"bp(GO:"microglial cell activation")"
"p(HGNC:"DPYSL2",pmod(Ph))"
frag("672_713"))",Y
Y
pmod(Ph))",Y
Y
frag("672_713")),p(HGNC:"C1QBP"))",Y
frag("672_713"))",Y
Y
"p(HGNC:"BACE1")"
"p(HGNC:"BCL2L1")"
"p(HGNC:"BACE1")"
"a(CHEBI:"calcium(2+)")"
"act(p(HGNC:"EIF2AK3"))"
var("E,280,A"))",Y
"bp(GO:"methylglyoxal catabolic process to lactate")"
"p(HGNC:"MAPT",var("P,S,199"))"
Y
"a(CHEBI:"amyloid-beta")"
Y
Y
Y
"p(HGNC:"LAMTOR3")"
"p(HGNC:"IL1B")"
"bp(GO:"positive regulation of mitochondrial membrane potential")"
"path(MESH:"Inflammation")"
Y
Y
Y
pmod(Glyco))",Y
"p(HGNC:"BACE1")"
Y
Y
"a(CHEBI:"copper(1+)")"
Y
Y
"a(CHEBI:"calcium(2+)")"
"p(HGNC:"DKK1")"
Y
Y
Y
Y
Y
"p(HGNC:"BACE1")"

### Causal-Only-Graph mined rules

### Origin-Graph mined rules